apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - server-sidecar-envoy-configmap.yaml
  - server-deployment.yaml
  - server-headless-service.yaml
  - client-sidecar-envoy-configmap.yaml
  - client-deployment.yaml
  - client-service.yaml
