// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rock-paper-scissors.proto

package rock_paper_scissors

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShowType int32

const (
	// グー
	ShowType_ROCK ShowType = 0
	// チョッキ
	ShowType_PAPER ShowType = 1
	// パー
	ShowType_SCISSORS ShowType = 2
)

var ShowType_name = map[int32]string{
	0: "ROCK",
	1: "PAPER",
	2: "SCISSORS",
}

var ShowType_value = map[string]int32{
	"ROCK":     0,
	"PAPER":    1,
	"SCISSORS": 2,
}

func (x ShowType) String() string {
	return proto.EnumName(ShowType_name, int32(x))
}

func (ShowType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_50b54ffabdaff6a6, []int{0}
}

type JankenRequest struct {
	ShowType             ShowType `protobuf:"varint,1,opt,name=show_type,json=showType,proto3,enum=ShowType" json:"show_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JankenRequest) Reset()         { *m = JankenRequest{} }
func (m *JankenRequest) String() string { return proto.CompactTextString(m) }
func (*JankenRequest) ProtoMessage()    {}
func (*JankenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b54ffabdaff6a6, []int{0}
}

func (m *JankenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JankenRequest.Unmarshal(m, b)
}
func (m *JankenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JankenRequest.Marshal(b, m, deterministic)
}
func (m *JankenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JankenRequest.Merge(m, src)
}
func (m *JankenRequest) XXX_Size() int {
	return xxx_messageInfo_JankenRequest.Size(m)
}
func (m *JankenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JankenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JankenRequest proto.InternalMessageInfo

func (m *JankenRequest) GetShowType() ShowType {
	if m != nil {
		return m.ShowType
	}
	return ShowType_ROCK
}

type JankenResponse struct {
	ShowType             ShowType `protobuf:"varint,1,opt,name=show_type,json=showType,proto3,enum=ShowType" json:"show_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JankenResponse) Reset()         { *m = JankenResponse{} }
func (m *JankenResponse) String() string { return proto.CompactTextString(m) }
func (*JankenResponse) ProtoMessage()    {}
func (*JankenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50b54ffabdaff6a6, []int{1}
}

func (m *JankenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JankenResponse.Unmarshal(m, b)
}
func (m *JankenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JankenResponse.Marshal(b, m, deterministic)
}
func (m *JankenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JankenResponse.Merge(m, src)
}
func (m *JankenResponse) XXX_Size() int {
	return xxx_messageInfo_JankenResponse.Size(m)
}
func (m *JankenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JankenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JankenResponse proto.InternalMessageInfo

func (m *JankenResponse) GetShowType() ShowType {
	if m != nil {
		return m.ShowType
	}
	return ShowType_ROCK
}

func init() {
	proto.RegisterEnum("ShowType", ShowType_name, ShowType_value)
	proto.RegisterType((*JankenRequest)(nil), "JankenRequest")
	proto.RegisterType((*JankenResponse)(nil), "JankenResponse")
}

func init() { proto.RegisterFile("rock-paper-scissors.proto", fileDescriptor_50b54ffabdaff6a6) }

var fileDescriptor_50b54ffabdaff6a6 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xca, 0x4f, 0xce,
	0xd6, 0x2d, 0x48, 0x2c, 0x48, 0x2d, 0xd2, 0x2d, 0x4e, 0xce, 0x2c, 0x2e, 0xce, 0x2f, 0x2a, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe7, 0xe2, 0xf5, 0x4a, 0xcc, 0xcb, 0x4e, 0xcd, 0x0b,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe3, 0xe2, 0x2c, 0xce, 0xc8, 0x2f, 0x8f, 0x2f,
	0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0xe2, 0xd4, 0x0b, 0xce, 0xc8, 0x2f,
	0x0f, 0xa9, 0x2c, 0x48, 0x0d, 0xe2, 0x28, 0x86, 0xb2, 0x94, 0x2c, 0xb8, 0xf8, 0x60, 0x1a, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x89, 0xd5, 0xa9, 0xa5, 0xcb, 0xc5, 0x01, 0x13, 0x15, 0xe2, 0xe0,
	0x62, 0x09, 0xf2, 0x77, 0xf6, 0x16, 0x60, 0x10, 0xe2, 0xe4, 0x62, 0x0d, 0x70, 0x0c, 0x70, 0x0d,
	0x12, 0x60, 0x14, 0xe2, 0xe1, 0xe2, 0x08, 0x76, 0xf6, 0x0c, 0x0e, 0xf6, 0x0f, 0x0a, 0x16, 0x60,
	0x32, 0x32, 0xe3, 0x62, 0x83, 0x58, 0x24, 0xa4, 0xc3, 0xc5, 0x1e, 0x94, 0x5a, 0x96, 0x5a, 0x54,
	0x9c, 0x2a, 0xc4, 0xa7, 0x87, 0xe2, 0x6a, 0x29, 0x7e, 0x3d, 0x54, 0xc7, 0x28, 0x31, 0x24, 0xb1,
	0x81, 0x3d, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x4a, 0xf4, 0xcc, 0xfd, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JankenClient is the client API for Janken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JankenClient interface {
	Reverse(ctx context.Context, in *JankenRequest, opts ...grpc.CallOption) (*JankenResponse, error)
}

type jankenClient struct {
	cc *grpc.ClientConn
}

func NewJankenClient(cc *grpc.ClientConn) JankenClient {
	return &jankenClient{cc}
}

func (c *jankenClient) Reverse(ctx context.Context, in *JankenRequest, opts ...grpc.CallOption) (*JankenResponse, error) {
	out := new(JankenResponse)
	err := c.cc.Invoke(ctx, "/Janken/Reverse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JankenServer is the server API for Janken service.
type JankenServer interface {
	Reverse(context.Context, *JankenRequest) (*JankenResponse, error)
}

// UnimplementedJankenServer can be embedded to have forward compatible implementations.
type UnimplementedJankenServer struct {
}

func (*UnimplementedJankenServer) Reverse(ctx context.Context, req *JankenRequest) (*JankenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reverse not implemented")
}

func RegisterJankenServer(s *grpc.Server, srv JankenServer) {
	s.RegisterService(&_Janken_serviceDesc, srv)
}

func _Janken_Reverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JankenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JankenServer).Reverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Janken/Reverse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JankenServer).Reverse(ctx, req.(*JankenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Janken_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Janken",
	HandlerType: (*JankenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reverse",
			Handler:    _Janken_Reverse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rock-paper-scissors.proto",
}
